repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    # trims all whitespace from the end of each line
    -   id: trailing-whitespace
    # ensures that all files end in a newline and only a newline
    -   id: end-of-file-fixer
    # replace "double quotes" by 'single quotes' unless "it's impossible"
    -   id: double-quote-string-fixer
    # prevents large files from being committed (>100kb)
    -   id: check-added-large-files
        args: [--maxkb=100]
    # enforce the naming conventions of test scripts
    -   id: name-tests-test
        # tests match test_.*\.py
        args: [--pytest-test-first]
        exclude: tests.modules.*

-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.3.0
    hooks:
    -   id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-angular']

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        additional_dependencies: [toml]

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
        name: Yapf
        additional_dependencies: [toml]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.220
    hooks:
    -   id: ruff
