name: Python package

on: [push, pull_request]

env:
  MIN_CODE_COVERAGE_PERCENT: 54

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Automated tests (with code coverage)
        run: poetry run pytest -v --cov=pydoctrace --cov-branch --cov-report term-missing --cov-fail-under $MIN_CODE_COVERAGE_PERCENT
