name: Python package

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  POETRY_VERSION: 1.8.3
  MIN_CODE_COVERAGE_PERCENT: 86

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'

      - name: Define a cache for the virtual environment based on the dependencies lock file
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Make pipx-installed packages available in the $PATH
        if: runner.os != 'Windows'
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install project dependencies
        run: poetry install --without lint

      - name: Run automated tests (with code coverage)
        run: poetry run pytest -v --cov=pydoctrace --cov-branch --cov-report term-missing --cov-fail-under $MIN_CODE_COVERAGE_PERCENT
